<a href="https://colab.research.google.com/github/peakodev/data_science_class/blob/main/PD21_M1_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Елементи лінійної алгебри

## Встановлення бібліотеки NumPy

In [ ]:
# !pip install numpy

In [ ]:
import numpy as np

## Вектори

Що таке вектор?

Вектор - це математичний об'єкт, що характеризується величиною (модулем) та напрямком. Його можна представити як напрямлений відрізок на площині або в просторі.

**Вектори в Data Science:** Вектори широко використовуються в Data Science для представлення різних даних, таких як:

Ознаки об'єкта: Наприклад, вектор [вік, зріст, вага] може представляти фізичні характеристики людини.
Часовий ряд: Вектор може містити значення певної величини в різні моменти часу, наприклад, ціни акцій за тиждень.
Вектори слів (word embeddings): В обробці природної мови слова представляються векторами, що відображають їх семантичне значення.


In [ ]:
import plotly.figure_factory as ff
import plotly.graph_objects as go

import numpy as np

def display_vectors(vectors: np.ndarray) -> None:

    if vectors.ndim == 1:
        x, y = [vectors[0]], [vectors[1]]
    elif vectors.ndim == 2:
        x, y = vectors[:, 0], vectors[:, 1]
    else:
        raise ValueError("Input must be either 1D or 2D")


    # Create quiver figure
    fig = ff.create_quiver(
        [0]*len(x), [0]*len(y),
        x, y,
        scale=1.0,
        arrow_scale=.2,
        name='vector',
        line_width=5
    )

    # Add points to figure
    fig.add_trace(go.Scatter(
        x=[0], y=[0],
        mode='markers',
        marker_size=12,
        name='center'
    ))

    fig.show()

Вектори в NumPy:

В NumPy вектори представляються як одновимірні масиви (ndarray).


### Створення вектора

In [ ]:
import numpy as np

vector = np.array([1, 2])

display_vectors(vector)

In [ ]:
type(vector)

numpy.ndarray

In [ ]:
vector * 2

array([ 2,  4,  6, 10, 12, 14, 16, 18])

### Додавання/віднімання скаляра

In [ ]:
import numpy as np

a = np.array([1, 2, 3], dtype=float)
print(a + 2)  # [3. 4. 5.]
print(a - 1)  # [0. 1. 2.]

[3. 4. 5.]
[0. 1. 2.]


### Множення на скаляр

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)

[1. 2. 3. 4. 5.]


In [ ]:
b = 5 * a
b

array([ 5., 10., 15., 20., 25.])

### Додавання та віднімання двох векторів

In [ ]:
import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])
print(a + b)
print(a - b)

[5 7]
[-3 -3]


### Скалярний добуток (Dot product)

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


print(np.dot(a, b))
print(a.dot(b))
print(a @ b)

32
32
32


## Матриці

In [ ]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(m)

[[1 2 3]
 [4 5 6]]


In [ ]:
m.shape

(2, 3)

In [ ]:
a = np.array([[2, 3, 4, 5],
              [1, 2, 3, 4]])

b = np.array([[2, 2, 2, 2], [2, 2, 2, 2]])

print(a*2)

[[ 4  6  8 10]
 [ 2  4  6  8]]


In [ ]:
def scale_by_2(var):
    return var * 2

scale_by_2(6)

12

### Множення матриць

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [0, 1, 2]])

b = np.array([[ 1, 2],
              [ 0, 4],
              [-1, 0]])

c = np.dot(a, b)
c = a.dot(b)
c = a @ b
print(c)

[[-2 10]
 [-2  4]]


### Транспонування матриці

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a)
b = a.T
print()
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6]]
)

b = a.reshape((1, 3, 2, -1))
print(b)

[[[[1]
   [2]]

  [[3]
   [4]]

  [[5]
   [6]]]]


In [ ]:
, 2 * 3

(2, 6)

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten()
print(b)

[1 2 3 4 5 6]


### Одинична матриця

In [ ]:
import numpy as np

a = np.eye(4, dtype=bool)

a * a
print(a)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


### Обернена матриця

In [ ]:
import numpy as np

a = np.array([[ 1, 0, 3],
              [-1,-1, 2],
              [ 4, 7, 2]], dtype=int)

a_inv = np.linalg.inv(a)
print(a_inv)

[[ 0.64 -0.84 -0.12]
 [-0.4   0.4   0.2 ]
 [ 0.12  0.28  0.04]]


In [ ]:
a_inv @ a

array([[ 1.00000000e+00,  3.05311332e-16, -3.88578059e-16],
       [-1.11022302e-16,  1.00000000e+00,  5.55111512e-17],
       [-2.77555756e-17, -2.08166817e-17,  1.00000000e+00]])

## Інші можливості в NumPy

In [ ]:
a = np.array([[ 1, 0, 3],
              [-1,-1, 2],
              [ 4, 7, 2]], dtype=float)

In [ ]:
a.size

9

In [ ]:
a.itemsize

8

In [ ]:
9*8

72

In [ ]:
import numpy as np

a = np.ones((5,), dtype=float)
print(a)

m = np.ones((2, 3), dtype=int)
print(m)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np

a = np.zeros(5, dtype=float)
print(a)

m = np.zeros((2, 3), dtype=int)
print(m)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


In [ ]:
for i in range(5, 1):
    print(i)

In [ ]:
import numpy as np

a = np.arange(5)
b = np.arange(1, 3, 0.5)
print(a)
print(b)

[0 1 2 3 4]
[1.  1.5 2.  2.5]


In [ ]:
import numpy as np

a = np.linspace(1, 10, num=20)
b = np.linspace(1, 3, num=3)
print(a)
print(b)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[1. 2. 3.]


In [ ]:
a = np.random.random(3) * 10
b = np.random.random((3, 3))
print(a)
print(b)

[4.13557964 3.79923894 0.10811704]
[[0.58402106 0.91277738 0.40059082]
 [0.19233625 0.74418522 0.27451853]
 [0.0517955  0.78822223 0.20419611]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[1:])
print(a[1:3])

1
[2 3 4 5]
[2 3]


In [ ]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(a[1, 1])
print(a[1:, 1])
print(a[0, :2, 2, 2])

5
[5 8]
[1 2]


In [ ]:
a

In [ ]:
list_1 = [1, 2, 3, 4]

list_1[1:-1]

[2, 3]

In [ ]:
b = np.array(["10", 2, 257], dtype=np.int16)
print(b)

b.dtype
b

[ 10   2 257]


array([ 10,   2, 257], dtype=int16)

In [ ]:
import numpy as np

a = np.array(["sdf", u"\u220F"], dtype="U")
print(a)  # ['∑' '∏']

['sdf' '∏']


In [ ]:
a = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

v = np.array([1, 2, 3, 4, 5],)

a * v

array([[ 1,  4,  9, 16, 25],
       [ 6, 14, 24, 36, 50]])

In [ ]:
import numpy as np

a = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.prod())

1
10
55
5.5
3628800


In [ ]:
100

In [ ]:
1 * 2 * 3 * 4 * 5

120

In [ ]:
2, 4

2 / 2 = 3

In [ ]:
a.dtype

dtype('float64')

In [ ]:
vector = np.array([1, 2])
display_vectors(vector)

In [ ]:
new_vector = vector - 1
print("vector", vector)
print("new_vector", new_vector)

display_vectors(np.array([vector, new_vector]))

vector [1 2]
new_vector [0 1]
